---
title: "Demo Dashboard"
output:
  flexdashboard::flex_dashboard:
    orientation: columns
  'flexdashboard::flex_dashboard: orientation: columns': default
---

# Intro{.sidebar}

This is a dashboard on a sample of sales data

- overview
- orders per continent
- orders by manager

# Overview 

## Column1


```{r message=FALSE, warning=FALSE}
library(tibble)
library(dplyr)
library(prettydoc)
library(readr)
library(readxl)
library(openxlsx)
library(flexdashboard)
library(ggplot2)

sales_data_sample <- read_excel("~/Documents/R/sales_data_sample.xlsx", 
    sheet = "sales_data_sample", skip = 3)

sales_data_sample <- sales_data_sample %>% 
  rename(quantity_ordered = `QUANTITY ORDERED`,
         price_each = `PRICE EACH`,
         country = COUNTRY,
         dealsize = DEALSIZE) %>% 
  mutate(continent = case_when(
           # We will cover shorter ways to do long match lists like this later
           country == "USA" ~ "North America",
           country == "France" ~ "Europe",
           country == "Norway" ~ "Europe",
           country == "Australia" ~ "Oceania",
           country == "Finland" ~ "Europe",
           country == "Austria" ~ "Europe",
           country == "UK" ~ "Europe", 
           country == "Spain" ~ "Europe",
           country == "Sweden" ~ "Europe",
           country == "Singapore" ~ "Asia",
           country == "Canada" ~ "North America",
           country == "Japan" ~ "Asia",
           country == "Italy" ~ "Europe",
           country == "Denmark" ~ "Europe",
           country == "Belgium" ~ "Europe",
           country == "Philippines" ~ "Asia",
           country == "Germany" ~ "Europe",
           country == "Switzerland" ~ "Europe",
           country == "Ireland" ~ "Europe"
         )) %>% 
  mutate(manager=case_when(
           dealsize == "Small" ~ "Tim",
           dealsize == "Medium" ~ "Olga",
           TRUE ~ "Sonia"))
```

### Total sales {.value-box}

```{r}
total_quantity <- 
  sales_data_sample %>% 
  summarise(total_sales = sum(quantity_ordered))

valueBox(total_quantity, caption = "Total quantity ordered", icon="fa-tag", color="info")
# > <span class="value-output" data-caption="Errors" data-icon="fa-random" data-color-accent="info">42</span>
```
### Each dot represents one sales point

```{r}
ggplot(data = sales_data_sample,
       mapping = aes(x = quantity_ordered, 
                     y = price_each,
                     color = continent)) + 
  geom_point() 
```

# Orders per continent 

## Column2

### Absolute

```{r message=FALSE, warning=FALSE}

n_of_order_per_continent <- 
  sales_data_sample %>% 
  group_by(continent, dealsize) %>% 
  summarise(n_of_order = n()) %>% 
  ungroup()

ggplot(data = n_of_order_per_continent,
       mapping = aes(x = continent,
                     y = n_of_order,
                     fill = dealsize)) +
  geom_col()  +
  labs(title = "Number of orders per continent",
       subtitle = "Colors represent dealsizes")
```

## Column3

### Relative

```{r message=FALSE, warning=FALSE}
pct_n_of_order_per_continent <- 
  n_of_order_per_continent %>% 
  group_by(continent) %>% 
  # Thanks to group_by, the sum() function will compute the sum for the continent
  mutate(pct_n_of_order = n_of_order / sum(n_of_order)) %>% 
  ungroup()

ggplot(data = pct_n_of_order_per_continent,
       mapping = aes(x = continent, 
                     y = pct_n_of_order,
                     fill = dealsize)) + 
  geom_col() +
  labs(title = "Relative number of orders per dealsize",
       subtitle = "Colors represent dealsizes")
```



# Orders by manager 

## Column4

### Orders by manager

```{r message=FALSE, warning=FALSE}

n_of_order_per_manager <- 
  sales_data_sample %>% 
  group_by(manager, dealsize) %>% 
  summarise(n_of_order = n()) %>% 
  ungroup()

ggplot(data = n_of_order_per_manager,
       mapping = aes(x = manager,
                     y = n_of_order,
                     fill = dealsize)) +
  geom_col()  +
  labs(title = "Number of orders per manager",
       subtitle = "Colors represent dealsizes")
```

## Column5

### Main KPI {.value-box}

```{r}
valueBox(42, caption = "KPI value", icon="fa-tag", color="info")
# > <span class="value-output" data-caption="Errors" data-icon="fa-random" data-color-accent="info">42</span>
```

### Other KPI as a gauge

```{r}
gauge(42, min = 0, max = 100, symbol = '%', gaugeSectors(
  success = c(80, 100), warning = c(40, 79), danger = c(0, 39)
))
```

