Scraping PETS 2024 accepted papers
================

## Accepted papers for PETS 2024, Privacy Enhancing technologies Symposium, Bristol, UK and Online

With this code I obtain a list of papers accepted at PETS 2024, made
available online freely at
<https://petsymposium.org/2024/paperlist.php>.

I read the html page of the website.

``` r
html_request <- read_html("https://petsymposium.org/2024/paperlist.php")
```

I view the extracted html separately and identify in it the list of
papers.

``` r
xml_child(xml_child(xml_child(xml_child(xml_child(html_request, 2), 1), 4), 3), 1)
```

    ## {html_node}
    ## <ul>
    ##  [1] <li>A Large-Scale Study of Cookie Banner Interaction Tools and their Imp ...
    ##  [2] <li>SoK: Data Privacy in Virtual Reality<br><span style="font-style: ita ...
    ##  [3] <li>Interest-disclosing Mechanisms for Advertising are Privacy-Exposing  ...
    ##  [4] <li>"Those things are written by lawyers, and programmers are reading th ...
    ##  [5] <li>Supporting Informed Choices about Browser Cookies: The Impact of Per ...
    ##  [6] <li>Block Cookies, Not Websites: Analysing Mental Models and Usability o ...
    ##  [7] <li>Mitigating Inference Risks with the NIST Privacy Framework<br><span  ...
    ##  [8] <li>Why Privacy-Preserving Protocols Are Sometimes Not Enough: A Case St ...
    ##  [9] <li>Generalizable Active Privacy Choice: Designing a Graphical User Inte ...
    ## [10] <li>Opted Out, Yet Tracked: Are Regulations Enough to Protect Your Priva ...
    ## [11] <li>Privacy Preserving Feature Selection for Sparse Linear Regression<br ...
    ## [12] <li>Model-driven Privacy<br><span style="font-style: italic;">Srdan Krst ...
    ## [13] <li>DP-ACT: Decentralized Privacy-Preserving Asymmetric Digital Contact  ...
    ## [14] <li>CoStricTor: Collaborative HTTP Strict Transport Security in Tor Brow ...
    ## [15] <li>DeVoS: Deniable Yet Verifiable Vote Updating<br><span style="font-st ...
    ## [16] <li>Over Fences and Into Yards: Privacy Threats and Concerns of Commerci ...
    ## [17] <li>Constant-Round Private Decision Tree Evaluation for Secret Shared Da ...
    ## [18] <li>Data Isotopes for Data Provenance in DNNs<br><span style="font-style ...
    ## [19] <li>MAPLE: MArkov Process Leakage attacks on Encrypted Search<br><span s ...
    ## [20] <li>SocIoTy: Practical At-Home Cryptography from IoT Devices<br><span st ...
    ## ...

I save several lists of authors&papers (4 in total). They are probably
saved in 4 different chuncks in the html file.

``` r
authors1 <- xml_child(xml_child(xml_child(xml_child(xml_child(html_request, 2), 1), 4), 3), 1) %>%
  rvest::html_nodes(css="span") %>% 
  html_text()
```

``` r
authors2 <- xml_child(xml_child(xml_child(xml_child(xml_child(html_request, 2), 1), 4), 5), 1) %>%
  rvest::html_nodes(css="span") %>% 
  html_text()
```

``` r
authors3 <- xml_child(xml_child(xml_child(xml_child(xml_child(html_request, 2), 1), 4), 8), 1) %>% 
  rvest::html_nodes(css="span") %>% 
  html_text()
```

``` r
authors4 <- xml_child(xml_child(xml_child(xml_child(xml_child(html_request, 2), 1), 4), 11), 1) %>% 
  rvest::html_nodes(css="span") %>% 
  html_text()
```

I group together all the paper information.

``` r
papers1 <- xml_child(xml_child(xml_child(xml_child(xml_child(html_request, 2), 1), 4), 3), 1) %>%
  rvest::html_nodes(css="li ") %>% 
  html_text2()

papers2 <- xml_child(xml_child(xml_child(xml_child(xml_child(html_request, 2), 1), 4), 5), 1) %>%
  rvest::html_nodes(css="li") %>% 
  html_text2()

papers3 <- xml_child(xml_child(xml_child(xml_child(xml_child(html_request, 2), 1), 4), 8), 1) %>% 
  rvest::html_nodes(css="li") %>% 
  html_text2()

papers4 <- xml_child(xml_child(xml_child(xml_child(xml_child(html_request, 2), 1), 4), 11), 1) %>% 
  rvest::html_nodes(css="li") %>% 
  html_text2()

accepted_papers <- bind_rows(as_tibble(papers1),
          as_tibble(papers2),
          as_tibble(papers3),
          as_tibble(papers4)) 
```

And save file as .csv file.

``` r
as_tibble(str_split_fixed(accepted_papers$value, "\n", 2)) %>% 
  rename("paper_name"="V1", "authors_list"="V2") %>% 
  write_csv("scraped_popets_2024.csv")
```

    ## Warning: The `x` argument of `as_tibble.matrix()` must have unique column names if
    ## `.name_repair` is omitted as of tibble 2.0.0.
    ## ℹ Using compatibility `.name_repair`.
    ## This warning is displayed once every 8 hours.
    ## Call `lifecycle::last_lifecycle_warnings()` to see where this warning was
    ## generated.

Now I separate authors and identify unique authors, and eventual
separation errors.

``` r
as_tibble(str_split_fixed(accepted_papers$value, "\n", 2)) %>% 
  rename("paper_name"="V1", "authors_list"="V2") %>% 
  mutate(split_list= str_split(authors_list, "\\)+\\,+\\s")) %>% # split where the patterns is "), "
  unnest_longer(split_list) %>% 
  mutate(split_list=str_replace(split_list, "^and ", "")) %>%  #remove "and " in the beginning of name
  mutate(split_list=str_replace(split_list, "\\)$", "")) %>% # remove parenthesis at end of name
  arrange(split_list) %>% 
  distinct(split_list, .keep_all = TRUE) # remove duplicates among authors
```

    ## # A tibble: 556 × 3
    ##    paper_name                                            authors_list split_list
    ##    <chr>                                                 <chr>        <chr>     
    ##  1 GenAIPABench: A Benchmark for Generative AI-based Pr… Aamir Hamid… Aamir Ham…
    ##  2 SublonK: Sublinear Prover PlonK                       Arka Rai Ch… Aarushi G…
    ##  3 MAPLE: MArkov Process Leakage attacks on Encrypted S… Seny Kamara… Abdelkari…
    ##  4 AUTOLYCUS: Exploiting Explainable Artificial Intelli… Abdullah Ca… Abdullah …
    ##  5 Traceable mixnets                                     Prashant Ag… Abhinav N…
    ##  6 Selective Authenticated Pilot Location Disclosure fo… Pietro Tede… Abu Dhabi…
    ##  7 Snail: Secure Single Iteration Localization           James Chonc… Ada Gavri…
    ##  8 How Does Connecting Online Activities to Advertising… Florian Far… Adam J. A…
    ##  9 Defining and Controlling Information Leakage in US E… Arthur Amer… Adam McKo…
    ## 10 Summary Reports Optimization in the Privacy Sandbox … Hidayet Aks… Adam Seal…
    ## # ℹ 546 more rows

There are a total of 556 unique authors in the originally-scraped file.
Among them there are a few limited cases where authors are not yet
split, and a few others where they are university or location names.

In the list of 18 below there are 17 new authors that I failed to split
before.

``` r
as_tibble(str_split_fixed(accepted_papers$value, "\n", 2)) %>% 
  rename("paper_name"="V1", "authors_list"="V2") %>% 
  mutate(split_list= str_split(authors_list, "\\)+\\,+\\s")) %>% # split where the patterns is "), "
  unnest_longer(split_list) %>% 
  mutate(split_list=str_replace(split_list, "^and ", "")) %>%  #remove "and " in the beginning of name
  mutate(split_list=str_replace(split_list, "\\)$", "")) %>% # remove parenthesis at end of name
  arrange(split_list) %>% 
  distinct(split_list, .keep_all = TRUE) %>% 
  filter(str_detect(split_list, "\\)+\\s+and"))
```

    ## # A tibble: 18 × 3
    ##    paper_name                                            authors_list split_list
    ##    <chr>                                                 <chr>        <chr>     
    ##  1 Deniability in Automated Contact Tracing: Impossibil… Christoph U… Christoph…
    ##  2 Mitigating Inference Risks with the NIST Privacy Fra… Christopher… Christoph…
    ##  3 Anonymous Complaint Aggregation for Secure Messaging  Connor Bell… Connor Be…
    ##  4 Revealing the True Cost of Locally Differentially Pr… Héber H. Ar… Héber H. …
    ##  5 Two Steps Forward and One Step Back: The Right to Op… Jan Charata… Jan Chara…
    ##  6 Post-quantum XML and SAML Single Sign-On              Johannes Mü… Johannes …
    ##  7 StyleAdv: A Usable Privacy Framework Against Facial … Minh-Ha Le … Minh-Ha L…
    ##  8 Evaluating Google's Protected Audience Protocol       Minjun Long… Minjun Lo…
    ##  9 Johnny Still Can’t Opt-out: Assessing the IAB CCPA C… Muhammad Ab… Muhammad …
    ## 10 FlashSwift: A Configurable and More Efficient Range … Nan Wang (C… Nan Wang …
    ## 11 Efficient Issuer-Hiding Authentication, Application … Olivier San… Olivier S…
    ## 12 Onion Services in the Wild: A Study of Deanonymizati… Pascal Tipp… Pascal Ti…
    ## 13 A Deniability Analysis of Signal’s Initial Handshake… Rune Fiedle… Rune Fied…
    ## 14 SoK: Metadata-Protecting Communication Systems        Sajin Sasy … Sajin Sas…
    ## 15 PRIVIC: A privacy-preserving method for incremental … Sayan Biswa… Sayan Bis…
    ## 16 The Medium is the Message: How Secure Messaging Apps… Nikita Sama… Serge Ege…
    ## 17 GCL-Leak: Link Membership Inference Attacks against … Xiuling Wan… Xiuling W…
    ## 18 Interest-disclosing Mechanisms for Advertising are P… Yohan Beugi… Yohan Beu…

I save them in a new list, which I split further.

``` r
new_list <- as_tibble(str_split_fixed(accepted_papers$value, "\n", 2)) %>% 
  rename("paper_name"="V1", "authors_list"="V2") %>% 
  mutate(split_list= str_split(authors_list, "\\)+\\,+\\s")) %>% # split where the patterns is "), "
  unnest_longer(split_list) %>% 
  mutate(split_list=str_replace(split_list, "^and ", "")) %>%  #remove "and " in the beginning of name
  mutate(split_list=str_replace(split_list, "\\)$", "")) %>% # remove parenthesis at end of name
  arrange(split_list) %>% 
  distinct(split_list, .keep_all = TRUE) %>% # remove duplicates, keep all columns
  filter(str_detect(split_list, "\\)+\\s+and")) %>% 
  mutate(split_additional=str_split(split_list, "\\)+\\s+and")) %>% #add new rows for the auhtors separated by ") and"
  unnest_longer(split_additional) %>% 
  select(paper_name, authors_list, split_additional) %>% 
  rename(split_list=split_additional)

new_list  
```

    ## # A tibble: 36 × 3
    ##    paper_name                                            authors_list split_list
    ##    <chr>                                                 <chr>        <chr>     
    ##  1 Deniability in Automated Contact Tracing: Impossibil… Christoph U… "Christop…
    ##  2 Deniability in Automated Contact Tracing: Impossibil… Christoph U… " Krzyszt…
    ##  3 Mitigating Inference Risks with the NIST Privacy Fra… Christopher… "Christop…
    ##  4 Mitigating Inference Risks with the NIST Privacy Fra… Christopher… " Joshua …
    ##  5 Anonymous Complaint Aggregation for Secure Messaging  Connor Bell… "Connor B…
    ##  6 Anonymous Complaint Aggregation for Secure Messaging  Connor Bell… " Saba Es…
    ##  7 Revealing the True Cost of Locally Differentially Pr… Héber H. Ar… "Héber H.…
    ##  8 Revealing the True Cost of Locally Differentially Pr… Héber H. Ar… " Sébasti…
    ##  9 Two Steps Forward and One Step Back: The Right to Op… Jan Charata… "Jan Char…
    ## 10 Two Steps Forward and One Step Back: The Right to Op… Jan Charata… " Eleanor…
    ## # ℹ 26 more rows

I then bind my new list to the original list, and deduplicate authors.

``` r
original_list <- as_tibble(str_split_fixed(accepted_papers$value, "\n", 2)) %>% 
  rename("paper_name"="V1", "authors_list"="V2") %>% 
  mutate(split_list= str_split(authors_list, "\\)+\\,+\\s")) %>% # split where the patterns is "), "
  unnest_longer(split_list) %>% 
  mutate(split_list=str_replace(split_list, "^and ", "")) %>%  #remove "and " in the beginning of name
  mutate(split_list=str_replace(split_list, "\\)$", "")) %>% # remove parenthesis at end of name
  arrange(split_list) %>% 
  distinct(split_list, .keep_all = TRUE)

original_list
```

    ## # A tibble: 556 × 3
    ##    paper_name                                            authors_list split_list
    ##    <chr>                                                 <chr>        <chr>     
    ##  1 GenAIPABench: A Benchmark for Generative AI-based Pr… Aamir Hamid… Aamir Ham…
    ##  2 SublonK: Sublinear Prover PlonK                       Arka Rai Ch… Aarushi G…
    ##  3 MAPLE: MArkov Process Leakage attacks on Encrypted S… Seny Kamara… Abdelkari…
    ##  4 AUTOLYCUS: Exploiting Explainable Artificial Intelli… Abdullah Ca… Abdullah …
    ##  5 Traceable mixnets                                     Prashant Ag… Abhinav N…
    ##  6 Selective Authenticated Pilot Location Disclosure fo… Pietro Tede… Abu Dhabi…
    ##  7 Snail: Secure Single Iteration Localization           James Chonc… Ada Gavri…
    ##  8 How Does Connecting Online Activities to Advertising… Florian Far… Adam J. A…
    ##  9 Defining and Controlling Information Leakage in US E… Arthur Amer… Adam McKo…
    ## 10 Summary Reports Optimization in the Privacy Sandbox … Hidayet Aks… Adam Seal…
    ## # ℹ 546 more rows

``` r
merged_list <- bind_rows(original_list, new_list)

merged_list %>% 
  arrange(split_list) %>% 
  distinct(split_list, .keep_all = TRUE)
```

    ## # A tibble: 591 × 3
    ##    paper_name                                            authors_list split_list
    ##    <chr>                                                 <chr>        <chr>     
    ##  1 Onion Services in the Wild: A Study of Deanonymizati… Pascal Tipp… " Adrian …
    ##  2 PRIVIC: A privacy-preserving method for incremental … Sayan Biswa… " Catusci…
    ##  3 A Deniability Analysis of Signal’s Initial Handshake… Rune Fiedle… " Christi…
    ##  4 Johnny Still Can’t Opt-out: Assessing the IAB CCPA C… Muhammad Ab… " Christo…
    ##  5 Evaluating Google's Protected Audience Protocol       Minjun Long… " David E…
    ##  6 FlashSwift: A Configurable and More Efficient Range … Nan Wang (C… " Dongxi …
    ##  7 Two Steps Forward and One Step Back: The Right to Op… Jan Charata… " Eleanor…
    ##  8 SoK: Metadata-Protecting Communication Systems        Sajin Sasy … " Ian Gol…
    ##  9 Efficient Issuer-Hiding Authentication, Application … Olivier San… " Jacques…
    ## 10 Post-quantum XML and SAML Single Sign-On              Johannes Mü… " Jan Oup…
    ## # ℹ 581 more rows

And in the list below we find the few erroneous separations that do not
contain names.

``` r
merged_list %>% 
  filter(str_length(split_list)<5)
```

    ## # A tibble: 2 × 3
    ##   paper_name                                             authors_list split_list
    ##   <chr>                                                  <chr>        <chr>     
    ## 1 Towards Biologically Plausible and Private Gene Expre… Dingfan Che… Bonn      
    ## 2 What Do Privacy Advertisements Communicate to Consume… Xiaoxin She… US

Thus, here is an improved list of 581 distinct authors, including the
papers they got accepted and their affiliations.

``` r
merged_list %>% 
  filter(str_length(split_list)>5, !str_detect(split_list, "Eindhoven, Netherlands"), !str_detect(split_list, "University of California, Berkeley")) # removing obviously wrong authors  
```

    ## # A tibble: 581 × 3
    ##    paper_name                                            authors_list split_list
    ##    <chr>                                                 <chr>        <chr>     
    ##  1 GenAIPABench: A Benchmark for Generative AI-based Pr… Aamir Hamid… Aamir Ham…
    ##  2 SublonK: Sublinear Prover PlonK                       Arka Rai Ch… Aarushi G…
    ##  3 MAPLE: MArkov Process Leakage attacks on Encrypted S… Seny Kamara… Abdelkari…
    ##  4 AUTOLYCUS: Exploiting Explainable Artificial Intelli… Abdullah Ca… Abdullah …
    ##  5 Traceable mixnets                                     Prashant Ag… Abhinav N…
    ##  6 Selective Authenticated Pilot Location Disclosure fo… Pietro Tede… Abu Dhabi…
    ##  7 Snail: Secure Single Iteration Localization           James Chonc… Ada Gavri…
    ##  8 How Does Connecting Online Activities to Advertising… Florian Far… Adam J. A…
    ##  9 Defining and Controlling Information Leakage in US E… Arthur Amer… Adam McKo…
    ## 10 Summary Reports Optimization in the Privacy Sandbox … Hidayet Aks… Adam Seal…
    ## # ℹ 571 more rows
